[profile.default]
libs = ['lib']
solc_version = "0.8.23" # Override for the solc version (setting this ignores `auto_detect_solc`)
evm_version = "paris"   # to prevent usage of PUSH0, which is not supported on all chains

optimizer = true
optimizer_runs = 200
test = 'test'

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[invariant]
runs = 32
depth = 128
fail_on_revert = true
